<a href="https://colab.research.google.com/github/Josh-techie/AI-TPs/blob/master/Basics-Python/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1> Assignment 3 : PYTHON  (Part3)</h1></center>
<center><h3>Chapter 3</h3></center>

---



## **Exercice I**
Define a class vecteur3d defined by the attributes ***x, y, z***

1. Introduce a member function named coincide to determine if two vectors have the same components.
2. Introduce a member function named normax to obtain, among two vectors, the one with the largest norm.
3. Overload the + operator so that the following instructions will be accepted:
   **v1 = vecteur3d(2, 3, 4), v2 = vecteur3d(0, 1, -1)**<br>
   **v3 = v1 + v2 // v3 will be (2, 4, 3)** <br>
4. Overload the ***print*** function in such a way that it displays the vector in the form ***(x, y, z)***
5. Provide a program (main) to call the various member functions of the vecteur3d class.


In [1]:
class vecteur3d:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def coincide(self, v):
        return self.x == v.x and self.y == v.y and self.z == v.z

    def normax(self, v):
        if self.x > v.x and self.y > v.y and self.z > v.z:
            return self
        else:
            return v

    def __add__(self, v):
        return vecteur3d(self.x + v.x, self.y + v.y, self.z + v.z)

    def __str__(self):
        return f'( {self.x}, {self.y}, {self.z} )'

v1 = vecteur3d(2, 3, 4)
v2 = vecteur3d(0, 1, -1)
v3 = v1 + v2
print(v3)

print(v1.coincide(v2))
print(v1.normax(v2))

( 2, 4, 3 )
False
( 2, 3, 4 )


## **Exercice II**
1. Create a class ***Article*** defined by the private attributes ***name*** (str), ***reference*** (str), ***unitPrice*** (float).
2. Define the accessor and mutator methods.
3. Define the class ***Pen*** that inherits from the ***Article*** class.
4. Add an attribute ***couleur*** to this class.
5. Define the accessor and mutator methods for this class.
6. Define another class ***Ream*** that inherits from the ***Article*** class and add an attribute ***format*** to the class.
7. Define a method ***getType()*** that displays the string "this is an article", "this is a ream" or "this is a pen" if the instance is of type ***Article***, ***Ream***, or ***Pen***, respectively.


In [9]:
class Article:
    def __init__(self, name, reference, unitPrice):
        self.name = name
        self.reference = reference
        self.unitPrice = unitPrice

    # Define accessor and mutator methods here


class Pen(Article):
    def __init__(self, name, reference, unitPrice, color):
        super().__init__(name, reference, unitPrice)
        self.color = color

    # Define accessor and mutator methods for Pen here


class Ream(Article):
    def __init__(self, name, reference, unitPrice, format):
        super().__init__(name, reference, unitPrice)
        self.format = format

    # Define accessor and mutator methods for Ream here

    def getType(self):
        return "this is a ream"


# Instantiate the classes and print them
article_instance = Article("Generic Article", "123", 10.99)
pen_instance = Pen("Blue Pen", "456", 1.99, "Blue")
ream_instance = Ream("A4 Ream", "789", 5.99, "A4")

print(article_instance.name, article_instance.reference, article_instance.unitPrice)
print(pen_instance.name, pen_instance.reference, pen_instance.unitPrice, pen_instance.color)
print(ream_instance.name, ream_instance.reference, ream_instance.unitPrice, ream_instance.format)
print(ream_instance.getType())  # Output: this is a ream


Generic Article 123 10.99
Blue Pen 456 1.99 Blue
A4 Ream 789 5.99 A4
this is a ream


## **Exercice III**
1. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
2. Write a NumPy program to create a 2D array (5x5) with 1 on the border and 0 inside.
3. Write a NumPy program to convert Celsius degree values to Fahrenheit degrees (°F = °C * 1.8 + 32.00).
4. Write a NumPy program to test if each element of a 1-D array is also present in a second array.<br>
Example:<br>
  Array1: [0 10 20 40 60]<br>
  Array2: [0 40]<br>
  Output: [True False False True False]<br>


In [10]:
import numpy as np

matrix_3x3 = np.arange(2, 11).reshape(3, 3)
print("1. 3x3 Matrix with values ranging from 2 to 10:")
print(matrix_3x3)

1. 3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print("\n2. 2D Array (5x5) with 1 on the border and 0 inside:")
print(array_2d)



2. 2D Array (5x5) with 1 on the border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
def celsius_to_fahrenheit(celsius_array):
    return celsius_array * 1.8 + 32.0

celsius_degrees = np.array([0, 25, 50, 75, 100])
fahrenheit_degrees = celsius_to_fahrenheit(celsius_degrees)
print("\n3. Celsius to Fahrenheit Conversion:")
print("Celsius Degrees:", celsius_degrees)
print("Fahrenheit Degrees:", fahrenheit_degrees)



3. Celsius to Fahrenheit Conversion:
Celsius Degrees: [  0  25  50  75 100]
Fahrenheit Degrees: [ 32.  77. 122. 167. 212.]


In [13]:
def test_element_presence(array1, array2):
    return np.isin(array1, array2)

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])
output = test_element_presence(array1, array2)
print("\n4. Test if each element of Array1 is present in Array2:")
print("Array1:", array1)
print("Array2:", array2)
print("Output:", output)



4. Test if each element of Array1 is present in Array2:
Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
Output: [ True False False  True False]
